cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'httrack'
brew 'imagemagick'
brew 'node'
brew 'openssl'
brew 'pandoc'
brew 'pandoc-citeproc'
brew 'pandoc-cross-ref'
brew 'readline'
brew 'unrar'
brew 'wget'

cask '1password'
cask 'bartender'
cask 'bettertouchtool'
cask 'caffeine'
cask 'caskroom/versions/sublime-text3'
cask 'cheatsheet'
cask 'cloudup'
cask 'dropbox'
cask 'fantastical'
cask 'flux'
cask 'google-chrome'
cask 'hazel'
cask 'iterm2'
cask 'launchbar'
cask 'mactex'
cask 'papers'
cask 'polymail'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'transmission'
